---

# Kubenrtes version, only support 1.4.0+
kube_version: 1.6.5

# Network implementation('flannel', 'calico')
network: flannel
pod_network_cidr: "10.244.0.0/16"

# When use vagrant to deploy, you should set to flannel: --iface=enp0s8. calico: interface=enp0s8 or can-reach=8.8.8.8
network_opts: ""

# Kubernetes cluster network
cluster_subnet: 192.160.0
kubernetes_service_ip: "{{ cluster_subnet }}.1"
service_ip_range: "{{ cluster_subnet }}.0/12"
service_node_port_range: 30000-32767
api_secure_port: 5443

# Set if you want to access kubernetes cluster via load balancer
lb_vip_address: 172.16.35.9
lb_secure_port: 6443
lb_api_url: "https://{{ lb_vip_address }}:{{ lb_secure_port }}"

# Etcd variable
etcd_domain_name: test.etcd.com # use to create wildcard ssl certificate for api and etcd
etcd_peer_url_scheme: http # http / https

# A list of insecure registrys you might need to define
insecure_registrys:
# - "gcr.io"

# Extra authenticating
extra_auth:
  basic:
    accounts:
    - 'p@ssw0rd,admin,admin'
  # abac:
  #   policies:
  #   - '{"user":"admin", "nonResourcePath": "*", "namespace": "*", "resource": "*", "apiGroup": "*"}'
  #   - '{"user":"kube-admin", "nonResourcePath": "*", "namespace": "*", "resource": "*", "apiGroup": "*"}'
  #   - '{"user":"kube-node", "nonResourcePath": "*", "namespace": "*", "resource": "*", "apiGroup": "*"}'
  #   - '{"user":"scheduler", "namespace": "*", "resource": "*", "apiGroup": "*"}'
  #   - '{"user":"kubelet", "namespace": "*", "resource": "*", "apiGroup": "*"}'
  #   - '{"group":"system:serviceaccounts", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}'
  # token:
  #   values:
  #   - '0fdd1a8875ec,admin,admin'

# Dashboard addon
kube_dash: true

# DNS service addon
kube_dns: true
dns_name: cluster.local # cluster dns name
dns_ip: "{{ cluster_subnet }}.10"

# Kubernetes proxy addon
kube_proxy: true
kube_proxy_mode: iptables # it should be "iptables",
                          # but if you want to deploy ceph on kubernetes,
                          # you must set to "userspace"
# EFK logging addon
kube_logging: false

# Grafana + Infuxdb monitoring addon
kube_monitoring: false

# Watch event addon
kube_watch: false
watch:
  slack:
    token: "<Slack legacy token>"
    channel: "<Slack channel>"

# Local Docker registry info
registry_ui: false
registry_port: 5000
registry_ui_port: 5001

# Enable offline pkg repository mode
repos_mode: false
repos_port: 4040
repos_url: "http://172.16.35.9:{{ repos_port }}"
