---
# Download container image

image_tmp: /tmp

images:
  pod_infra: # registry.access.redhat.com/rhel7/pod-infrastructure
    name: pause
    repos: gcr.io/google_containers/
    tag: "3.0"
  apiserver:
    name: kube-apiserver-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  manager: # 'quay.io/attcomdev/kube-controller-manager:v{{ kube_version }}' for ceph storage class
    name: kube-controller-manager-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  scheduler:
    name: kube-scheduler-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  haproxy:
    name: haproxy
    repos: kairen/
    tag: "1.7"
  keepalived:
    name: keepalived
    repos: kairen/
    tag: "1.2.24"
  calico_node:
    name: node
    repos: quay.io/calico/
    tag: "v1.1.3"
  calico_pollicy:
    name: kube-policy-controller
    repos: quay.io/calico/
    tag: "v0.5.4"
  # Addons container images
  proxy:
    name: kube-proxy-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  dashboard:
    name: kubernetes-dashboard-amd64
    repos: gcr.io/google_containers/
    tag: "v1.6.3"
  dns:
    name: kubedns-amd64
    repos: gcr.io/google_containers/
    tag: "1.9"
  dnsmasq:
    name: kube-dnsmasq-amd64
    repos: gcr.io/google_containers/
    tag: "1.4"
  healthz:
    name: exechealthz-amd64
    repos: gcr.io/google_containers/
    tag: "1.2"
  fluentd_es:
    name: fluentd-elasticsearch
    repos: gcr.io/google_containers/
    tag: "1.23"
  elasticsearch:
    name: elasticsearch
    repos: gcr.io/google_containers/
    tag: "v2.4.1-2"
  kibana:
    name: kibana
    repos: gcr.io/google_containers/
    tag: "v4.6.1-1"
  heapster:
    name: heapster-amd64
    repos: gcr.io/google_containers/
    tag: "v1.4.0"
  hp_influx:
    name: heapster-influxdb-amd64
    repos: gcr.io/google_containers/
    tag: "v1.1.1"
  hp_grafana:
    name: heapster-grafana-amd64
    repos: gcr.io/google_containers/
    tag: "v4.0.2"
  # Other container images
  registry:
    name: registry
    repos: kairen/
    tag: "2.6.1"
  registry_ui:
    name: docker-registry-ui
    repos: parabuzzle/
    tag: "2.1.3"
  repos:
    name: pkg-repos
    repos: kairen/
    tag: "0.1.0"
# OS images
  baseimage:
    name: baseimage
    repos: "phusion/"
    tag: "0.9.22"
  ubuntu:
    name: ubuntu
    repos: ""
    tag: "16.04"
  centos:
    name: centos
    repos: ""
    tag: "7"
  redhat:
    name: redhat
    repos: "hjd48/"
    tag: "latest"
  rhel7:
    name: redhat
    repos: "aossama/"
    tag: "rhel7"
  fedora:
    name: fedora
    repos: ""
    tag: "25"
  busybox:
    name: busybox
    repos: ""
    tag: "1.26"
  # Dev images
  java:
    name: java
    repos: ""
    tag: "7"
  gcc:
    name: gcc
    repos: ""
    tag: "7"
  php:
    name: php
    repos: ""
    tag: "7"
  python:
    name: python
    repos: ""
    tag: "2.7"
  perl:
    name: perl
    repos: ""
    tag: "5"
  # Application images
  nginx:
    name: nginx
    repos: ""
    tag: "1.13"
  httpd:
    name: httpd
    repos: ""
    tag: "2.4-alpine"
  mysql:
    name: mysql
    repos: ""
    tag: "8"
  hello_world:
    name: hello-world
    repos: ""
    tag: latest
  hadoop:
    name: hadoop-docker
    repos: "sequenceiq/"
    tag: 2.7.1
