---

# System dir path
systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
dropin_dir: /usr/lib/systemd/system
ceph_config_dir: /etc/ceph

# Kubernetes component
cert_dir: /opt/cert/pki
kube_etc_dir: /etc/kubernetes
kube_manifest_dir: "{{ kube_etc_dir }}/manifests"
kube_cert_dir: "{{ kube_etc_dir }}/pki"
kube_addon_dir: "{{ kube_etc_dir }}/addon"
kube_network_dir: "{{ kube_etc_dir }}/network"
kubelet_config: "{{ kube_etc_dir }}/kubelet.conf"
kubeadmin_config: "{{ kube_etc_dir }}/admin.conf"
cni_etc_dir: "/etc/cni/net.d"

# TSL certificate
sa_key: "{{ kube_cert_dir }}/apiserver-key.pem"
ca_cert: "{{ kube_cert_dir }}/ca.pem"
ca_key: "{{ kube_cert_dir }}/ca-key.pem"
api_cert: "{{ kube_cert_dir }}/apiserver.pem"
admin_key: "{{ kube_cert_dir }}/admin-key.pem"
admin_cert: "{{ kube_cert_dir }}/admin.pem"
node_cert: "{{ kube_cert_dir }}/node.pem"
node_key: "{{ kube_cert_dir }}/node-key.pem"

# Etcd config
etcd_conf_dir: /etc/etcd
etcd_data_dir: /var/lib/etcd

# Etcd certificate
etcd_ca_file: "{{ kube_cert_dir }}/ca.pem"
etcd_cert_file: "{{ kube_cert_dir }}/etcd.pem"
etcd_key_file: "{{ kube_cert_dir }}/etcd-key.pem"
etcd_peer_ca_file: "{{ kube_cert_dir }}/ca.pem"
etcd_peer_cert_file: "{{ kube_cert_dir }}/etcd.pem"
etcd_peer_key_file: "{{ kube_cert_dir }}/etcd-key.pem"
