---
# Download binary package from source

download_tmp: /tmp

pkg_bases:
  kube:
    url: "https://storage.googleapis.com"
    version: "{{ kube_version }}"
  etcd:
    url: "https://github.com"
    version: 3.2.1
  docker:
    url: "https://get.docker.com"
    version: 17.05.0-ce
  cni:
    url: "https://github.com"
    version: 0.5.2
  calicoctl:
    url: "https://github.com"
    version: 1.5.0
  helm:
    url: "https://kubernetes-helm.storage.googleapis.com"
    version: 2.6.2
  cfssl:
    url: "https://pkg.cfssl.org"
    version: 1.2

downloads:
  kube:
    name: kube
    description: "Kubernetes"
    dir: /opt/kube
    url: "{{ pkg_bases.kube.url }}/kubernetes-release/release/v{{ pkg_bases.kube.version }}/bin/linux/amd64"
    items: [ kubelet, kubectl ]
  etcd:
    name: etcd
    description: "Etcd key/value store"
    dir: /opt/etcd
    url: "{{ pkg_bases.etcd.url }}/coreos/etcd/releases/download/v{{ pkg_bases.etcd.version }}"
    unarchive:
      extra_opt: "['--strip-components=1']"
    items: [ "etcd-v{{ pkg_bases.etcd.version }}-linux-amd64.tar.gz" ]
  docker:
    name: docker
    description: "Docker engine"
    dir: /opt/docker
    url: "{{ pkg_bases.docker.url }}/builds/Linux/x86_64"
    unarchive:
      extra_opt: "['--strip-components=1']"
    items: [ "docker-{{ pkg_bases.docker.version }}.tgz" ]
  cni:
    name: cni
    description: "Container network interface"
    dir: /opt/cni/bin
    url: "{{ pkg_bases.cni.url }}/containernetworking/cni/releases/download/v{{ pkg_bases.cni.version }}"
    items: [ "cni-amd64-v{{ pkg_bases.cni.version }}.tgz" ]
    unarchive:
      extra_opt: "['--strip-components=0']"
  calicoctl:
    name: calicoctl
    description: "Calicoctl network plugin"
    dir: /opt/calico
    url: "{{ pkg_bases.calicoctl.url }}/projectcalico/calicoctl/releases/download/v{{ pkg_bases.calicoctl.version }}"
    items: [ calicoctl ]
  helm:
    name: helm
    description: "Kubernetes package manager"
    dir: /opt/helm
    url: "{{ pkg_bases.helm.url }}"
    unarchive:
      extra_opt: "['--strip-components=1']"
    items: [ "helm-v{{ pkg_bases.helm.version }}-linux-amd64.tar.gz" ]
  cfssl:
    name: cfssl
    description: "Cloudflare's PKI and TLS toolkit"
    dir: /opt/cfssl
    url: "{{ pkg_bases.cfssl.url }}/R{{ pkg_bases.cfssl.version }}"
    items: [ cfssl_linux-amd64, cfssljson_linux-amd64 ]
