---

- name: Create Kubernetes config directory
  file:
    path: "{{ kube_manifest_dir }}"
    state: directory

- name: Create Kubernetes config home directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy Kubernetes apiserver yml config file
  template:
    src: "kube-apiserver.yml.j2"
    dest: "{{ kube_manifest_dir }}/apiserver.manifest"

- name: Copy Kubernetes controller-manager yml config file
  template:
    src: "kube-controller-manager.yml.j2"
    dest: "{{ kube_manifest_dir }}/controller-manager.manifest"

- name: Copy Kubernetes scheduler yml config file
  template:
    src: "kube-scheduler.yml.j2"
    dest: "{{ kube_manifest_dir }}/scheduler.manifest"

- name: Copy Kubernetes admin account config file
  template:
    src: "admin.conf.j2"
    dest: "{{ kubeadmin_config }}"

- name: Copy Kubernetes admin config to home directory
  template:
    src: "admin.conf.j2"
    dest: "{{ ansible_env.HOME }}/.kube/config"

- name: Create Kubernetes pki directory
  file:
    path: "{{ kube_etc_dir }}/pki/"
    state: directory

- name: Copy helmrc file
  when: helm_init
  copy:
    src: helmrc
    dest: "{{ ansible_env.HOME }}"

- name: Copy SSL certificate from ansible host
  copy:
    src: "{{ cert_dir }}"
    dest: "{{ kube_etc_dir }}"
