---

- name: Create Kubernetes config directory
  file:
    path: "{{ kube_manifest_dir }}"
    state: directory

- name: Create Kubernetes config home directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy Kubernetes apiserver yml config file
  template:
    src: "kube-apiserver.yml.j2"
    dest: "{{ kube_manifest_dir }}/apiserver.manifest"

- name: Copy Kubernetes controller-manager yml config file
  template:
    src: "kube-controller-manager.yml.j2"
    dest: "{{ kube_manifest_dir }}/controller-manager.manifest"

- name: Copy Kubernetes scheduler yml config file
  template:
    src: "kube-scheduler.yml.j2"
    dest: "{{ kube_manifest_dir }}/scheduler.manifest"

- name: Copy Kubernetes admin account config file
  template:
    src: "admin.conf.j2"
    dest: "{{ kubeadmin_config }}"

- name: Copy Kubernetes admin config to home directory
  template:
    src: "admin.conf.j2"
    dest: "{{ ansible_env.HOME }}/.kube/config"

- name: Copy SSL certificate from ansible host
  copy:
    src: "{{ cert_dir }}"
    dest: "{{ kube_etc_dir }}"

- name: Create Kubernetes component symlinks
  file:
    src: "{{ downloads.kube.dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items: [ kubectl, kubelet ]

- name: Create Kubernetes Helm symlinks
  file:
    src: "{{ downloads.helm.dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items: [ helm ]

- name: Create Calico ctl symlinks
  when: network == 'calico'
  file:
    src: "{{ downloads.calicoctl.dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items: [ calicoctl ]
