---
- name: Install Kubernetes Node packages
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    -  kubelet
    -  kubernetes-cni
  register: nodepackage

- name: add kubelet service file
  copy: src=kubelet.service dest=/etc/systemd/system/kubelet.service owner=root group=root mode=0755
  register: kubelet

- name: create kubernetes manifest config directory
  file: path={{ manifest_config_dir }} state=directory
  register: manifest

- name: create weave dir
  when: weave_net
  file: path={{ weavedir }} state=directory

- name: copy weave file
  when: weave_net
  copy: src=10-weave.conf  dest=/etc/cni/net.d/10-weave.conf

- name: create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory
  register: config_dir

- name: copy kubeadmin config file
  template: src="kubeadminconfig.j2" dest={{ kube_config_dir }}/kubeadminconfig
  register: config

- name: copy kubelet config file
  template: src="kubelet.j2" dest={{ kube_config_dir }}/kubelet
  register: kubeletconfig

- name: copy kube config file
  template: src="kubeletconfig.j2" dest={{ kube_config_dir }}/kubeletconfig
  register: kube_config

- name: create ssl cert dir
  file: path={{ cert_dir }} state=directory
  register: ssl_dir

- name: copy CA certificate from ansible host
  template: src={{ master_cert_dir }}/{{ item }} dest={{ cert_dir }}/{{ item }}
  with_items:
    - "ca-key.pem"
    - "ca.pem"
    - "admin.pem"
    - "admin-key.pem"
  register: ca_cert

- name: copy openssl
  when: ca_cert|changed
  template: src="openssl.conf.j2" dest={{ kube_config_dir }}/pki/openssl.conf
  register: openssl_config

- name: create certificate for node
#  when: openssl_config|changed
  register: create_ssl_cert
  command: "{{ item }}"
  with_items:
    - "openssl genrsa -out {{ cert_dir }}/node-key.pem 2048"
    - "openssl req -new -key {{ cert_dir }}/node-key.pem -out {{ cert_dir }}/node.csr -subj '/CN=kube-node' -config {{ cert_dir }}/openssl.conf"
    - "openssl x509 -req -in {{ cert_dir }}/node.csr -CA {{ cert_dir }}/ca.pem -CAkey {{ cert_dir }}/ca-key.pem -CAcreateserial -out {{ cert_dir }}/node.pem -days 1000 -extensions v3_req -extfile {{ cert_dir }}/openssl.conf"

- name: create kubelet directory
  file: path=/var/lib/kubelet state=directory

- name: start and enable kubelet on node
  service: name=kubelet enabled=no state=started
  register: kubelet_start_node

- name: reload kubelet
  when: create_ssl_cert|changed or kubelet|changed or kubeletconfig|changed
  service: name=kubelet state=restarted
