---

- name: Stop kubelet systemd service
  systemd: name=kubelet.service state=stopped enabled=no
  ignore_errors: True
  register: stop_kubelet_service

- name: Clean docker containers
  when: container_runtime == 'docker'
  shell: |
    {{ bin_dir }}/docker stop $(docker ps -aq) && \
      {{ bin_dir }}/docker rm $(docker ps -aq)
  ignore_errors: True
  register: clean_docker_containers

- name: Clean docker images
  when: container_runtime == 'docker'
  shell: |
    {{ bin_dir }}/docker rmi $(docker images -aq)
  ignore_errors: True
  register: clean_docker_images

- name: Stop docker systemd service
  when: container_runtime == 'docker' and clean_docker_images
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - docker.service
    - docker.socket
  ignore_errors: True
  register: stop_docker_service

- name: Stop containerd systemd service
  when: container_runtime == 'containerd'
  systemd: name=containerd.service state=stopped enabled=no
  ignore_errors: True
  register: stop_containerd_service

- name: Find kubelet mounted volumes
  when: stop_kubelet_service
  shell: "df | grep -o '/var/lib/kubelet.*'"
  ignore_errors: True
  register: find_mounts

- name: Unmounting kubelet volumes
  when: find_mounts
  mount: name={{ item }} state=unmounted
  with_items: "{{ find_mounts.stdout_lines | list }}"
  ignore_errors: True

- name: Delete component directorys
  when: stop_kubelet_service
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ etc_dir }}"
    - "{{ cni_etc_dir }}"
    - "{{ kubelet_config_dir }}"
    - "{{ audit_log_dir }}"
    - "{{ haproxy_config_dir }}"
    - "{{ ansible_env.HOME }}/.kube"
    - "{{ ansible_env.HOME }}/.helm"
    - "{{ docker_data_dir }}"
    - "{{ containerd_data_dir }}"
    - "{{ package.docker.dir }}"
    - "{{ package.containerd.dir }}"
    - "{{ package.kubelet.dir }}"
    - "{{ package.helm.dir }}"
    - "{{ package.cfssl.dir }}"
    - "{{ package.cni.dir }}"
  ignore_errors: True

- name: Delete IP-in-IP tunnel
  when: stop_kubelet_service
  command: "modprobe -r ipip"
  ignore_errors: True

- name: Find network interfaces for Kubernetes
  when: stop_kubelet_service
  shell: "ip addr | grep {{ item }}"
  with_items:
    - "docker0"
    - "flannel.1"
    - "cni0"
    - "tunl0"
  register: find_eths
  ignore_errors: True

- name: Delete network interfaces for Kubernetes
  when: stop_kubelet_service and item.stdout != ''
  shell: "ip link delete {{ item.item }}"
  with_items: "{{ find_eths['results'] }}"
  ignore_errors: True

- name: Find blackhole route rule
  when: stop_kubelet_service
  shell: "ip route | awk '/blackhole/ {print $2}'"
  register: find_blackhole
  ignore_errors: True

- name: Delete blackhole route rule
  when: stop_kubelet_service and find_blackhole.stdout != ''
  shell: "ip route del {{ find_blackhole.stdout }}"
  ignore_errors: True
