---

kube_version: 1.14.3

# Container runtime,
# Supported: docker, nvidia-docker, containerd.
container_runtime: docker

# Container network,
# Supported: calico, flannel.
cni_enable: true
container_network: calico

# Kubernetes HA extra variables.
vip_interface: ""
vip_address: 172.16.35.9

# Kubernetes extra addons
enable_ingress: false
enable_dashboard: false
enable_logging: false
enable_monitoring: false
enable_metric_server: false