---

- name: Create Kubernetes addon directory
  file: path="{{ kube_addon_dir }}/{{ addon.name }}" state=directory

- name: "Copy {{ addon.name }} yml files"
  template:
    src: "{{ addon.name }}/{{ item.yaml }}.j2"
    dest: "{{ kube_addon_dir }}/{{ addon.name }}/{{ item.yaml }}"
  with_items: "{{ addon['files'] }}"

- name: Create Kubernetes dashboard certificate
  when: kube_dashboard
  include: config-dashboard.yml

- name: "Check {{ addon.name }} resource already exists"
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get {{ item.resource }} -n kube-system  | grep {{ item.name }}
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_res
  ignore_errors: true
  with_items: "{{ addon['files'] }}"

- name: "Create {{ addon.name }} resources"
  when: item.failed
  vars:
    file: "{{ item.item }}"
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            apply -f {{ kube_addon_dir }}/{{ addon.name }}/{{ file.yaml }}
  delegate_to: "{{ groups['masters'][0] }}"
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true
  with_items: "{{ check_res['results'] }}"
